spring:
  application:
    name: sms-service
  profiles:
    include: 'kafka'
    active: 'local'
  cloud:
    loadbalancer:
      ribbon:
        enable: false

server:
  port: 9020


---
spring:
  profiles:
    active: k8s
  cloud:
    loadbalancer:
      ribbon:
        enable: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

