spring:
  application:
    name: member-service
  profiles:
    include: 'kafka'
    active: 'local'
  cloud:
    loadbalancer:
      ribbon:
        enable: false

server:
  port: 9010


sms:
  exam:
    url: 'http://localhost:9020'

---
spring:
  profiles:
    active: k8s
  cloud:
    loadbalancer:
      ribbon:
        enable: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
server:
  port: 8080

sms:
  exam:
    url: 'http://sms-service.default.svc.cluster.local:8080'