apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    ms-name: member-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service-back-deploy
  namespace: default
  annotations:
    kubernetes.io/change-cause: init
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      ms-name: member-service
  template:
    metadata:
      name: member-service-pod
      namespace: default
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: member-service
          ports:
            - containerPort: 8080
          image: member-service-image:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            failureThreshold: 4
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 40

